name: visdial
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip:
    - accelerate==0.14.0.dev0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==22.1.0
    - bert-score==0.3.7
    - click==8.1.3
    - clip==1.0
    - contourpy==1.0.5
    - cycler==0.11.0
    - datasets==2.6.1
    - dill==0.3.5.1
    - evaluate==0.3.0
    - filelock==3.8.0
    - fonttools==4.37.4
    - frozenlist==1.3.1
    - fsspec==2022.10.0
    - ftfy==6.1.1
    - huggingface-hub==0.10.0
    - inexactsearch==1.0.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - matplotlib==3.6.1
    - multidict==6.0.2
    - multiprocess==0.70.13
    - nltk==3.7
    - packaging==21.3
    - pandas==1.5.0
    - psutil==5.9.2
    - pyarrow==10.0.0
    - pyparsing==3.0.9
    - pyspellchecker==0.7.0
    - python-dateutil==2.8.2
    - pytz==2022.4
    - pyyaml==6.0
    - regex==2022.9.13
    - responses==0.18.0
    - scikit-learn==1.1.3
    - silpa-common==0.3
    - soundex==1.1.3
    - spellchecker==0.4
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - tqdm==4.64.1
    - transformers==4.22.2
    - wcwidth==0.2.5
    - xxhash==3.1.0
    - yarl==1.8.1
